language: java
sudo: false
jdk:
  - oraclejdk8
branches:
  only:
    - master
script:
  - mvn clean package
after_success:
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: heroku
  app: "build-reports"
    api_key:
      secure: "f48f765f-7a12-4214-9a5d-ac23d8c01b58"
