language: java
before_script:
  - echo "Starting build"
script:
  - mvn clean package
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
  - echo "Build was failed"
branches:
  only:
    - master
deploy:
  provider: heroku
  app: "build-reports"
  api_key:
    secure: "f48f765f-7a12-4214-9a5d-ac23d8c01b58"
